AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-node

  Sample SAM Template for sam-node

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  PetsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pets/
      Handler: handlers.handler
      Runtime: nodejs14.x
  RecipesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: recipes/
      Handler: handlers.handler
      Runtime: nodejs14.x

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PetsFunction:
    Description: "Pets Lambda Function ARN"
    Value: !GetAtt PetsFunction.Arn
  PetsFunctionIamRole:
    Description: "Implicit IAM Role created for Pets function"
    Value: !GetAtt PetsFunctionRole.Arn
  RecipesFunction:
    Description: "Recipes Lambda Function ARN"
    Value: !GetAtt RecipesFunction.Arn
  RecipesFunctionIamRole:
    Description: "Implicit IAM Role created for Recipes function"
    Value: !GetAtt RecipesFunctionRole.Arn